spring.application.name=LojaCarro

# Configurações de Conexão para o Banco H2 em Memória
spring.datasource.url=jdbc:h2:mem:lojacarros;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Configurações JPA/Hibernate específicas para o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações JWT
app.jwtSecret=mySecretKeyForJWTTokenGenerationAndValidationOfTheApplicationv1v1v1v1v1v1v1v1v1v1v1v1v1v1v1v1
app.jwtExpirationMs=86400000

# Logging
logging.level.br.org.edu.ifrn.LojaCarro=DEBUG
